# Generated by Django 4.2.2 on 2023-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderCount',
            field=models.IntegerField(default=0),
        ),
    ]
