# Generated by Django 4.2.2 on 2023-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_ordercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://www.careeraddict.com/uploads/article/60419/entrepreneurship-product-ideas.png', max_length=200),
        ),
    ]
